apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: ypevzv3ee-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: ypevzv3ee-go 
  name: ypevzv3ee-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: ypevzv3ee-go 
